#ifndef POSELIB_VERSION_
#define POSELIB_VERSION_

#define POSELIB_MAJOR_VERSION ()
#define POSELIB_MINOR_VERSION ()
#define POSELIB_PATCH_VERSION ()
#define POSELIB_VERSION "2.0.0"

#endif  // POSELIB_VERSION_
